// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufzczyzugdrmnwjbooei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmemN6eXp1Z2RybW53amJvb2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODU3NjMsImV4cCI6MjA2ODM2MTc2M30.Icd8qRfoGCY1wf7Dkan30WRFRa4Oh4uc8SQIbnZw8ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});